fixtures:
  repositories:
    apt: 'git://github.com/puppetlabs/puppetlabs-apt.git'
    gnome: 'git://github.com/camptocamp/puppet-gnome.git'
    stdlib: 'git://github.com/puppetlabs/puppetlabs-stdlib.git'
  symlinks:
    adapta_gtk_theme: "#{source_dir}"
